export const AIRTABLE_BASE_ID = "appVy9thv2l5e9JKv";

export const tables = {
  courses: { id: "tbl3nkjD0LefcY3t9", name: "Courses" },
  generalEducation: { id: "tbl3Beqraxljn1aDm", name: "General Education Requirements" },
  assignments: { id: "tbllXlXa7oKsoFMae", name: "Assignments" },
  gradeCategories: { id: "tblXC0Vug7xyPFZqW", name: "Category Weights" },
  inboxItems: { id: "tblpTfEK98iyHCaEb", name: "Inbox Items" },
  habits: { id: "tblnPymbsaGbAtuum", name: "Habits" },
  habitCheckIns: { id: "tblYMLiIEVUkQZmre", name: "Habit Check-ins" },
  competencies: { id: "tblHueT6K8XC9qore", name: "Competencies" },
  competencyFocuses: { id: "tblki8BjyEGdd6V1c", name: "Competency Focuses" },
  contacts: { id: "tblcB7zTektBmiE0a", name: "Contacts" },
  organizations: { id: "tbleiFGpFYM2CsxlT", name: "Organizations" },
  interactions: { id: "tblftj2Pi29aZXoQY", name: "Interactions" },
  outreachOpportunities: { id: "tblMl1hG6lMJudlCy", name: "Outreach Opportunities" },
  importantDates: { id: "tblVfgNW5Zwn2PrQT", name: "Important Dates" }
} as const;

export const fields = {
  courses: {
    name: "Course Name",
    status: "Status",
    quarterTaken: "Quarter Taken",
    grade: "Grade",
    majorRequirements: "Major Requirements",
    geRequirementsUsed: "GE Requirements Used",
    creditHours: "Credit Hours"
  },
  generalEducation: {
    category: "Category"
  },
  assignments: {
    title: "Assignment Name",
    course: "Courses",
    dueAt: "Due Date",
    pointsEarned: "Points Earned",
    pointsPossible: "Points Possible",
    completed: "Completed",
    hiddenFromList: "Hidden from List",
    gradeCategory: "Category Weights",
    typeLabel: "General Assignment Type",
    weekLabel: "Week"
  },
  gradeCategories: {
    name: "Category Weight Name",
    course: "Courses",
    weightPercent: "Weight (%)",
    calculationType: "Calculation Type",
    maxExtraCreditPercent: "Max Extra Credit (%)"
  },
  inboxItems: {
    text: "Text",
    createdAt: "Created At",
    processed: "Processed"
  },
  habits: {
    name: "Name",
    targetDaysPerWeek: "Target Days per Week",
    status: "Status",
    createdAt: "Created At",
    sortOrder: "Sort Order"
  },
  habitCheckIns: {
    key: "Key",
    habit: "Habit",
    date: "Date",
    createdAt: "Created At"
  },
  competencies: {
    name: "Name",
    category: "Category",
    status: "Status",
    vision: "Vision",
    description: "Description",
    sortOrder: "Sort Order",
    createdAt: "Created At"
  },
  competencyFocuses: {
    title: "Title",
    competency: "Competency",
    startedAt: "Started At",
    endedAt: "Ended At",
    notes: "Notes",
    endReason: "End Reason",
    createdAt: "Created At"
  },
  contacts: {
    name: "Name",
    course: "Course",
    role: "Role",
    email: "Email",
    officeHours: "Office Hours",
    location: "Location",
    notes: "Notes",
    sourceEvent: "Source Event",
    sourceKey: "Source Key",
    codeLabPriority: "CodeLab Priority",
    codeLabFitReason: "CodeLab Fit Reason",
    potentialProjectAngles: "Potential Project Angles",
    generatedReachOutReason: "Generated Reach Out Reason",
    generatedProjectIdeas: "Generated Project Ideas",
    generatedDiscoveryPrompts: "Generated Discovery Prompts",
    generatedCodeLabScore: "Generated CodeLab Score",
    generatedTechRelevanceScore: "Generated Tech Relevance Score",
    generatedAuthorityScore: "Generated Authority Score",
    generatedProjectSourceScore: "Generated Project Source Score",
    generatedWarmPathScore: "Generated Warm Path Score",
    generatedScoreReason: "Generated Score Reason",
    generatedClientFitUpdatedAt: "Generated Client Fit Updated At",
    generatedClientFitVersion: "Generated Client Fit Version",
    outreachStatus: "Outreach Status",
    linkedInUrl: "LinkedIn URL",
    linkedInConnectedOn: "LinkedIn Connected On",
    identityStatus: "Identity Status",
    organizationMatchStatus: "Organization Match Status",
    evidenceNotes: "Evidence Notes",
    lastReviewedAt: "Last Reviewed At",
    prospectType: "Prospect Type",
    seniority: "Seniority",
    function: "Function",
    company: "Company",
    headline: "Headline",
    linkedInHeadline: "LinkedIn Headline",
    source: "Source",
    searchTerm: "Search Term",
    contactSegment: "Contact Segment",
    connectionDegree: "Connection Degree",
    studentStatus: "Student Status",
    projectPotential: "Project Potential",
    reviewStatus: "Review Status",
    duplicateKey: "Duplicate Key",
    duplicateGroup: "Duplicate Group",
    autoPriority: "Auto Priority",
    autoStudentStatus: "Auto Student Status",
    autoSeniority: "Auto Seniority",
    autoSource: "Auto Source",
    autoSearchTerm: "Auto Search Term",
    autoFunctionTags: "Auto Function Tags",
    autoProspectType: "Auto Prospect Type",
    autoProjectPotential: "Auto Project Potential",
    autoHeadline: "Auto Headline",
    autoCompany: "Auto Company",
    autoDuplicateGroup: "Auto Duplicate Group",
    autoDuplicateKey: "Auto Duplicate Key",
    autoReviewStatus: "Auto Review Status",
    workflows: "Workflows",
    relationshipType: "Relationship Type",
    personalPriority: "Personal Priority",
    relationshipRisk: "Relationship Risk",
    outreachReadiness: "Outreach Readiness",
    relationshipContext: "Relationship Context",
    researchStatus: "Research Status",
    researchDossier: "Research Dossier",
    researchSourceUrls: "Research Source URLs",
    lastResearchedAt: "Last Researched At",
    birthday: "Birthday",
    lastContacted: "Last Contacted",
    nextFollowUp: "Next Follow Up",
    organizations: "Organizations",
    interactions: "Interactions",
    outreachOpportunities: "Outreach Opportunities",
    importantDates: "Important Dates",
    autoWorkflowTags: "Auto Workflow Tags"
  },
  organizations: {
    name: "Organization Name",
    type: "Organization Type",
    website: "Website",
    linkedInUrl: "LinkedIn URL",
    verificationStatus: "Verification Status",
    evidenceUrls: "Evidence URLs",
    description: "Description",
    techRelevance: "Tech Relevance",
    notes: "Notes",
    contacts: "Contacts",
    outreachOpportunities: "Outreach Opportunities"
  }
} as const;

export function tableRef(key: keyof typeof tables): string {
  return tables[key].id;
}
